# fly.toml file generated for lively-wildflower-4369 on 2021-07-23T11:51:19+07:00

app = "lively-wildflower-4369"

kill_signal = "SIGTERM"
kill_timeout = 5

[env]

[[services]]
  http_checks = []
  internal_port = 4000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
