name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23.3.4'
          elixir-version: '1.12.2'
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test --cover
